# 09. Data Dictionary: User Onboarding Module

## Purpose
This document defines the data elements required for the User Onboarding and Identity Verification module in Project HelpLocal. It provides technical specifications for database schemas, front-end validation rules, and API payload structures.

---

## 1. User Authentication Table (Core Schema)

| Field Name | Data Type | Length / Format | Required? | Validation Rules / Business Logic | Example |
| :--- | :--- | :--- | :--- | :--- | :--- |
| `user_id` | Alphanumeric (UUID) | 36 characters | **Yes** | System-generated unique identifier (Primary Key). Cannot be modified. | `1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed` |
| `mobile_number` | String | E.164 format (`+[country][number]`) | **Yes** | Must look up against existing records to prevent duplicate accounts. | `+12345678901` |
| `account_type` | String (Enum) | `REQUESTOR` \| `VOLUNTEER` | **Yes** | Restricts the user dashboard view and functional permissions upon login. | `VOLUNTEER` |
| `verification_status` | String (Enum) | `UNVERIFIED` \| `PENDING` \| `VETTED` \| `REJECTED` | **Yes** | Default state is `UNVERIFIED`. Automatically updates to `PENDING` upon ID submission. | `PENDING` |

---

## 2. Security & Verification Log (Transient Schema)

| Field Name | Data Type | Length / Format | Required? | Validation Rules / Business Logic | Example |
| :--- | :--- | :--- | :--- | :--- | :--- |
| `otp_token` | Numeric | 6 digits | **Yes** | Cryptographically secure random integer generated by the backend server. | `482019` |
| `otp_generated_at` | Timestamp | `YYYY-MM-DD HH:MM:SS UTC` | **Yes** | Captured at moment of token generation. Used to compute token expiration. | `2026-05-21 18:30:00` |
| `id_image_binary` | BLOB / Binary | Max 5MB | **Yes** (Volunteers only) | Front-end must validate file size before payload delivery. Cleared from cache post-verification. | *[Binary Stream]* |
| `stripe_callback_id` | Alphanumeric | Max 255 characters | No | The unique transaction reference ID returned by the Stripe Identity API webhook. | `si_1N2M3L4K5J` |
